package mar15

fun main() {

    // exception

    // is abnormality in code

    // exception is not an error

    // exception vs error

    // exception is recoverable , usually exetion occurs because of user's fault

    // error is irrecoverable // stack  // heap  // jvm

    // compile exception (checked exception) // run time exception (un-checked exception)

    // compile // FileNotFoundException // SqlException // ClassNotFoundException

    // runtime Exception


    val n = 23

//    println(n/0)   // ArithmeticException

    val arr = intArrayOf(1,2,3,4,5)

//    println(arr[10])   // .ArrayIndexOutOfBoundsException

    //////////////////////////////////////////////////////

    val name = "Hello Student"

//    println(name[30])

    //////////////////////////////////////////////////////

    val data = "Hello"

    println(data.toInt())

    /////////////////////////////////////////////////////

    println("body.......")


}